CREATE TABLE tasks (
    task_id TEXT PRIMARY KEY NOT NULL,
    submission_key TEXT NOT NULL,
    site_id TEXT NOT NULL,
    content_type TEXT NOT NULL CHECK(content_type IN ('POST','PAGE')),
    topic TEXT NOT NULL,
    brief TEXT NOT NULL,
    brand_profile_id TEXT NOT NULL,
    request_snapshot TEXT NOT NULL CHECK(request_snapshot IS NULL OR json_valid(request_snapshot)),
    approval_policy_snapshot TEXT NOT NULL CHECK(approval_policy_snapshot IS NULL OR json_valid(approval_policy_snapshot)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    client_profile_id TEXT,
    target_audience TEXT,
    page_purpose TEXT,
    client_brand_snapshot TEXT NOT NULL CHECK(client_brand_snapshot IS NULL OR json_valid(client_brand_snapshot)),
    status TEXT NOT NULL CHECK(status IN ('QUEUED','CLAIMED','RUNNING','AWAITING_APPROVAL','FAILED','WORKER_LOST','APPROVED','PUBLISHING','PUBLISHED','PUBLISH_FAILED','TERMINATED')),
    current_run_id TEXT,
    latest_content_version_id TEXT,
    UNIQUE(submission_key),
    UNIQUE(task_id, content_type),
    FOREIGN KEY(task_id,current_run_id) REFERENCES task_runs(task_id,run_id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(task_id,latest_content_version_id) REFERENCES content_versions(task_id,content_version_id) DEFERRABLE INITIALLY DEFERRED
) STRICT;
CREATE TABLE task_runs (
    run_id TEXT PRIMARY KEY NOT NULL,
    task_id TEXT NOT NULL,
    attempt INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    run_mode TEXT NOT NULL CHECK(run_mode IN ('INITIAL','REVISION')),
    status TEXT NOT NULL CHECK(status IN ('QUEUED','CLAIMED','RUNNING','AWAITING_APPROVAL','FAILED','WORKER_LOST','APPROVED','PUBLISHING','PUBLISHED','PUBLISH_FAILED','TERMINATED')),
    owner_id TEXT,
    fencing_token INTEGER NOT NULL,
    workflow_state TEXT CHECK(workflow_state IS NULL OR json_valid(workflow_state)),
    claimed_at TEXT,
    started_at TEXT,
    heartbeat_at TEXT,
    finished_at TEXT,
    error TEXT CHECK(error IS NULL OR json_valid(error)),
    resumed_from_run_id TEXT,
    resumed_from_checkpoint_id TEXT,
    UNIQUE(task_id,attempt),
    UNIQUE(task_id,run_id),
    UNIQUE(task_id,run_id,attempt),
    FOREIGN KEY(task_id) REFERENCES tasks(task_id),
    FOREIGN KEY(task_id,resumed_from_run_id) REFERENCES task_runs(task_id,run_id),
    CHECK(attempt>0),
    CHECK(fencing_token>=0)
) STRICT;
CREATE TABLE task_events (
    event_id TEXT PRIMARY KEY NOT NULL,
    event_key TEXT NOT NULL,
    task_id TEXT NOT NULL,
    sequence_number INTEGER NOT NULL,
    type TEXT NOT NULL,
    actor TEXT NOT NULL,
    summary TEXT NOT NULL,
    created_at TEXT NOT NULL,
    run_id TEXT,
    attempt INTEGER,
    status TEXT CHECK(status IN ('QUEUED','CLAIMED','RUNNING','AWAITING_APPROVAL','FAILED','WORKER_LOST','APPROVED','PUBLISHING','PUBLISHED','PUBLISH_FAILED','TERMINATED')),
    detail TEXT,
    visibility TEXT NOT NULL,
    metadata TEXT NOT NULL CHECK(metadata IS NULL OR json_valid(metadata)),
    UNIQUE(event_key),
    UNIQUE(task_id,sequence_number),
    FOREIGN KEY(task_id) REFERENCES tasks(task_id),
    FOREIGN KEY(task_id,run_id,attempt) REFERENCES task_runs(task_id,run_id,attempt),
    CHECK((run_id IS NULL AND attempt IS NULL) OR (run_id IS NOT NULL AND attempt IS NOT NULL)),
    CHECK(sequence_number>0)
) STRICT;
CREATE TABLE content_versions (
    content_version_id TEXT PRIMARY KEY NOT NULL,
    task_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    version_number INTEGER NOT NULL,
    content_type TEXT NOT NULL CHECK(content_type IN ('POST','PAGE')),
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    validation_result TEXT NOT NULL CHECK(validation_result IS NULL OR json_valid(validation_result)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('QUEUED','CLAIMED','RUNNING','AWAITING_APPROVAL','FAILED','WORKER_LOST','APPROVED','PUBLISHING','PUBLISHED','PUBLISH_FAILED','TERMINATED')),
    excerpt TEXT,
    image_data TEXT CHECK(image_data IS NULL OR json_valid(image_data)),
    seo_metadata TEXT CHECK(seo_metadata IS NULL OR json_valid(seo_metadata)),
    optimization_report TEXT CHECK(optimization_report IS NULL OR json_valid(optimization_report)),
    taxonomy TEXT CHECK(taxonomy IS NULL OR json_valid(taxonomy)),
    suggested_slug TEXT,
    aeo_data TEXT CHECK(aeo_data IS NULL OR json_valid(aeo_data)),
    geo_data TEXT CHECK(geo_data IS NULL OR json_valid(geo_data)),
    structured_data TEXT CHECK(structured_data IS NULL OR json_valid(structured_data)),
    source_references TEXT CHECK(source_references IS NULL OR json_valid(source_references)),
    UNIQUE(task_id,version_number),
    UNIQUE(task_id,content_version_id),
    FOREIGN KEY(task_id,run_id) REFERENCES task_runs(task_id,run_id),
    FOREIGN KEY(task_id,content_type) REFERENCES tasks(task_id,content_type),
    CHECK(version_number>0),
    CHECK(aeo_data IS NULL AND geo_data IS NULL AND structured_data IS NULL AND source_references IS NULL)
) STRICT;
CREATE TRIGGER task_events_no_update BEFORE UPDATE ON task_events BEGIN SELECT RAISE(ABORT, 'Immutable history'); END;
CREATE TRIGGER task_events_no_delete BEFORE DELETE ON task_events BEGIN SELECT RAISE(ABORT, 'Immutable history'); END;
CREATE TRIGGER content_versions_no_update BEFORE UPDATE ON content_versions BEGIN SELECT RAISE(ABORT, 'Immutable history'); END;
CREATE TRIGGER content_versions_no_delete BEFORE DELETE ON content_versions BEGIN SELECT RAISE(ABORT, 'Immutable history'); END;
CREATE TRIGGER tasks_immutable BEFORE UPDATE OF task_id,submission_key,site_id,content_type,topic,brief,target_audience,page_purpose,brand_profile_id,client_profile_id,request_snapshot,approval_policy_snapshot,client_brand_snapshot,created_at ON tasks BEGIN SELECT RAISE(ABORT, 'Immutable request'); END;
CREATE INDEX runs_queue ON task_runs(status,created_at,run_id);
CREATE INDEX tasks_recent ON tasks(created_at,task_id);
